%
function standard_figure_render(src, evn,...
          model, paraID, contourVar, dataRange, deformedScale, deformedFlag,...
          nominalFlag,contourFlag)

stationID=fix(get(src,'value'))+1;

animationDelay=0;
animateFlag=false;
opt=1;

render_contour(model,...
                paraID,...
                stationID,...
                contourVar,...
                dataRange,...
                deformedScale,...
                deformedFlag,...
                animationDelay,...
                animateFlag,...
                opt,...
                nominalFlag,contourFlag)
