% Extract status of model parameters (as stored on ".EnableReset")
function modelParaStatus=modelGetParametersStatus(modelPara, X, inputData)

% Input:
% modelPara: input model parameters as generated by "modelGetParameters" [nPara x 7]
% X: paramaters value => [nSimulation x nPara]
% inputData: input model as initialised by "initInputDatabase" [nSimulation x nStation]

% Output:
% modelParaStatus=[nSimulation x nPara x nStation]
%----------------------

% Initialise the outputs
nPara=size(modelPara,1);
nSimulation=length(inputData);
nStation=length(inputData{1});

modelParaStatus=zeros(nSimulation, nPara, nStation);

for paraID=1:nPara
    fieldName=modelPara{paraID,3};
    fieldID=modelPara{paraID,4};
    
    for stationID=1:nStation
        for simID=1:nSimulation
            data.Input=inputData{simID}{stationID};
            [f, ~]=retrieveStructure(data, fieldName, fieldID);
            
            % update
            if strcmp(modelPara{paraID,7},'N/A') 
                 modelParaStatus(simID, paraID, stationID)=X(simID, paraID);
            else     
                [flagInput, ~]=checkInputStatus(f, 1, fieldName);
                if strcmp(modelPara{paraID,7},'ON/OFF') % categorical 
                    if flagInput % calculated
                        modelParaStatus(simID, paraID, stationID)=f.EnableReset;
                    else % failed to compute
                        modelParaStatus(simID, paraID, stationID)=0;
                    end
                else % continous                    
                    if flagInput && f.EnableReset % enabled
                        modelParaStatus(simID, paraID, stationID)=X(simID, paraID);
                    else % not enabled
                        modelParaStatus(simID, paraID, stationID)=0;
                    end
                end
            end
            
        end
    end
    
end
    
